### ISSUE TITLE
Banning by server

### ISSUE THREAD

**Issue by jamesbmoran** [stacompsoc/slither.ai#8]
After a period of time playing with the current version of the game, the web socket is closed by the server. This is probably due to an anti-AI detection system. They could possibly be measuring the rate of packets sent, banning when this is above a certain threshold.
This is supported by the fact that when I increase the frame rate, from its current 50ms to 10ms, the closing of the web socket was faster. Also when I increased it to 100ms, it wasn't closed until the snake died at around 400 points.
I decreased from 100ms to 50ms finding no problems until I came very close to 50. There for I think the threshold for rate of packs sent in order to result in a ban is >1packet/50ms
I recommend setting the rate it updates to every 55ms in order to maximise the ai's reaction time while having a reasonable buffer to avoid getting banned

**Comment by FMarno** [comment]
Great job James
